name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  build-package-and-publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"
      - name: Bump version to release
        run: sed -i "s/v0.0.0/$RELEASE_VERSION/" ./package.json
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
        working-directory: ./react/human-task-material-renderers
      - name: Install dependencies required to build package
        run: yarn install
        working-directory: ./react/human-task-material-renderers
      - name: Build package
        run: yarn build
        working-directory: ./react/human-task-material-renderers
      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./react/human-task-material-renderers
